const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=58',
  'https://sanand0.github.io/tdsdata/js_table/?seed=59',
  'https://sanand0.github.io/tdsdata/js_table/?seed=60',
  'https://sanand0.github.io/tdsdata/js_table/?seed=61',
  'https://sanand0.github.io/tdsdata/js_table/?seed=62',
  'https://sanand0.github.io/tdsdata/js_table/?seed=63',
  'https://sanand0.github.io/tdsdata/js_table/?seed=64',
  'https://sanand0.github.io/tdsdata/js_table/?seed=65',
  'https://sanand0.github.io/tdsdata/js_table/?seed=66',
  'https://sanand0.github.io/tdsdata/js_table/?seed=67',
];

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  let grandTotal = 0;

  for (const url of urls) {
    await page.goto(url, { waitUntil: 'networkidle' });

    // Wait for table to load (it's dynamically generated by JS)
    await page.waitForSelector('table');

    const pageSum = await page.evaluate(() => {
      let sum = 0;
      // Get all table cells
      document.querySelectorAll('td').forEach(cell => {
        const val = parseFloat(cell.innerText);
        if (!isNaN(val)) sum += val;
      });
      return sum;
    });

    console.log(`Sum for ${url}: ${pageSum}`);
    grandTotal += pageSum;
  }

  console.log(`Total sum across all pages: ${grandTotal}`);
  await browser.close();
})();
```

Click **"Commit new file"** (green button at the bottom).

---

## Step 3: Create the GitHub Actions Workflow

This is the file that tells GitHub *when and how* to run your script automatically.

In your repo, click **"Add file"** → **"Create new file"**

In the filename box, type exactly:
```
.github/workflows/scrape.yml
